# Generated by Django 6.0.6 on 2026-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_af",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Naam (Afrikaans)"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author_email",
            field=models.EmailField(max_length=254, verbose_name="E-pos / Email"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author_name",
            field=models.CharField(max_length=100, verbose_name="Naam / Name"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(verbose_name="Kommentaar / Comment"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body_af",
            field=models.TextField(blank=True, verbose_name="Inhoud (Afrikaans)"),
        ),
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.TextField(
                blank=True, help_text="Short summary shown on the list page"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="excerpt_af",
            field=models.TextField(blank=True, verbose_name="Uittreksel (Afrikaans)"),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title_af",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Titel (Afrikaans)"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
