# Generated by Django 6.0.6 on 2026-06-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genealogy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="date",
            field=models.CharField(
                blank=True,
                help_text="GEDCOM datum, bv. 1923 of ABT 1900",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.CharField(
                blank=True, help_text="GEDCOM datum, bv. EST 1900", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="marriage",
            name="end_date",
            field=models.CharField(
                blank=True, help_text="GEDCOM datum", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="marriage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="marriage",
            name="marriage_date",
            field=models.CharField(
                blank=True, help_text="GEDCOM datum, bv. 15 JAN 1920", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="pendingedit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="birth_date",
            field=models.CharField(
                blank=True,
                help_text="GEDCOM datum, bv. BEF 15 JAN 1900",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="death_date",
            field=models.CharField(
                blank=True, help_text="GEDCOM datum, bv. AFT 1950", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
