# Generated by Django 6.0.6 on 2026-06-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genealogy", "0002_alter_auditlog_id_alter_document_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name_plural": "Mense",
            },
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Geskep"),
                    ("update", "Gewysig"),
                    ("delete", "Verwyder"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="date",
            field=models.CharField(
                blank=True,
                help_text="GEDCOM datum, bv. 12/08/1923 of BEF/AFT/EST/ABT 1900",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("birth_certificate", "Geboorte Sertifikaat"),
                    ("death_certificate", "Dood Sertifikaat"),
                    ("marriage_certificate", "Huwelik Sertifikaat"),
                    ("divorce_paper", "Skeibrief"),
                    ("annulment_certificate", "Nietigverklaring Sertifikaat"),
                    ("adoption_paper", "Aanneming Papiere"),
                    ("guardianship_paper", "Voogdyskap Papiere"),
                    ("baptism", "Doop Sertifikaat"),
                    ("immigration", "Immigrasie Rekord"),
                    ("emigration", "Emigrasie Rekord"),
                    ("military", "Militêre Rekord"),
                    ("graduation", "Diploma of Graad"),
                    ("census", "Sensus Rekord"),
                    ("photo", "Foto"),
                    ("letter", "Brief"),
                    ("will", "Testament"),
                    ("other", "Ander"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.CharField(
                blank=True,
                help_text="GEDCOM datum, bv. 12/08/1923 of BEF/AFT/EST/ABT 1900",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("birth", "Geboorte"),
                    ("death", "Sterfte"),
                    ("baptism", "Doop"),
                    ("immigration", "Immigrasie"),
                    ("emigration", "Emigrasie"),
                    ("military_service", "Militêre Diens"),
                    ("graduation", "Graduering"),
                    ("other", "Ander"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="marriage",
            name="status",
            field=models.CharField(
                choices=[
                    ("married", "Getroud"),
                    ("divorced", "Geskei"),
                    ("widowed", "Nagelaat"),
                    ("separated", "Vervreemd"),
                    ("annulled", "Nietig Verklaar"),
                ],
                default="married",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pendingedit",
            name="action",
            field=models.CharField(
                choices=[("create", "Nuwe Rekord"), ("update", "Wysig Rekord")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pendingedit",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Hangende Beoordeling"),
                    ("approved", "Goedgekeur"),
                    ("rejected", "Verwerp"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Manlik"),
                    ("F", "Vroulik"),
                    ("O", "Ander"),
                    ("U", "Onbekend"),
                ],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("parent", "Ouer"),
                    ("adoptive_parent", "Aangenome Ouer"),
                    ("step_parent", "Stief Ouer"),
                    ("guardian", "Voog"),
                ],
                default="parent",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("pending", "Hangende Beoordeling"),
                    ("viewer", "Kyker"),
                    ("trusted", "Vertroude Lid"),
                    ("admin", "Administrateur"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
