# Generated by Django 6.0.6 on 2026-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genealogy", "0003_alter_person_options_alter_auditlog_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="people/photos/"),
        ),
    ]
