# Generated by Django 6.0.6 on 2026-07-02 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genealogy", "0004_alter_person_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="genealogy.event",
            ),
        ),
    ]
