# Generated by Django 6.0.6 on 2026-07-04 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genealogy", "0005_document_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["first_name", "last_name"],
                "verbose_name_plural": "Mense",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="marriage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="genealogy.marriage",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="relationship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="genealogy.relationship",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="is_root",
            field=models.BooleanField(
                default=False, help_text="Stam-ouer van die boom (a1)"
            ),
        ),
    ]
