# Generated by Django 6.0.6 on 2026-07-10 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genealogy", "0006_alter_person_options_document_marriage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="main_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Hoofpersoon waaraan die dokument gekoppel word",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_events",
                to="genealogy.person",
            ),
        ),
    ]
